### ISSUE TITLE
Dockerfile, missing tqdm dependency

### ISSUE THREAD

**Issue by napulen** [sander-wood/autoharmonizer#1]
I was successfully able to run this code (for inference) in a GPU-powered WSL2 Windows 10 installation, using the following `Dockerfile`:

```dockerfile
FROM tensorflow/tensorflow:2.2.0-gpu
WORKDIR /home/autoharmonizer
COPY . .
RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip3 install music21==6.7.1
RUN pip3 install keras==2.3.0
RUN pip3 install keras-metrics==1.1.0
RUN pip3 install tqdm==4.62.3
CMD ["bash"]
```

then

```bash
docker build -t autoharmonizer .
docker run -it --gpus all autoharmonizer
```

The information in the `README` was very helpful. Thank you. 

However, you are missing `tqdm` in your dependencies. It seems this version made it for me:

```python
tqdm==4.62.3
```

Leaving the `Dockerfile` in case it is helpful. Maybe worth having it in the `README`.

Cheers.

**Comment by sander-wood** [comment]
This is the version of tqdm that I am using. Thank you for your advice.
